apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "velero-notifications.fullname" . }}
  namespace: {{ .Values.namespace | default "velero" | quote }}
  labels:
    app: "velero-notifications"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "velero-notifications.fullname" .}}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- if .Values.deploymentLabels }}
    {{- toYaml .Values.deploymentLabels | nindent 4 }}
    {{- end }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  {{- if .Values.deploymentAnnotations }}
  {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: velero-notifications
  template:
    metadata:
      labels:
        app: "velero-notifications"
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/name: {{ include "velero-notifications.fullname" .}}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      {{- if .Values.podLabels }}
      {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.podAnnotations }}
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      annotations:
        configHash: {{ include "velero-notifications.confighash" . }}
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: velero-notifications
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      {{- if .Values.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName | quote }}
      {{- end }}
      initContainers:
        - name: "fix-keepalive"
          image: busybox:1.28
          command:
            - sh
            - -c
            - sysctl net.ipv4.tcp_keepalive_time=10 net.ipv4.tcp_keepalive_intvl=5 net.ipv4.tcp_keepalive_probes=3
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: "100m"
              memory: "96Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
      containers:
        - name: velero-notifications
          image: {{ .Values.image.repository | default "ghcr.io/zokeber/velero-notifications" }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          volumeMounts:
            - name: config-volume
              mountPath: /config/config.yaml
              subPath: config.yaml
          resources:
            {{- with .Values.resources }}
            {{- toYaml . | nindent 12 }}
            {{- else }}
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "32Mi"
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "velero-notifications.fullname" . }}-config