apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-notifications
  namespace: {{ .Values.namespace | default .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-notifications
rules:
  - apiGroups: ["velero.io"]
    resources: ["backups"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-notifications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: velero-notifications
subjects:
  - kind: ServiceAccount
    name: velero-notifications
    namespace: {{ .Values.namespace | default .Release.Namespace }}