name: Build and push container image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: v1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Application version
        id: semantic-version
        uses: paulhatch/semantic-version@v5.4.0
  
  build-push-container-images:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ghcr.io/bsdigital/velero-notifications:latest
            ghcr.io/bsdigital/velero-notifications:${{needs.build.outputs.version}}
